//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BinLocation
    {
        [Key]
        public int BinLocId { get; set; }
        public string BinLocation1 { get; set; }
        public int WarehouseId { get; set; }
        public string SL1 { get; set; }
        public string SL2 { get; set; }
        public string SL3 { get; set; }
        public string SL4 { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
