//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{
    public partial class Material
    {
        [Key]
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public bool IsActive { get; set; }
        public bool IsInventory { get; set; }
        public bool IsSales { get; set; }
        public bool IsPurchase { get; set; }
        public string Remark { get; set; }
        public int MaterialGroupId { get; set; }
        public int MaterialTypeId { get; set; }
        public int HSNId { get; set; }
        public string MaterialImage { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int CompanyId { get; set; }
    }
}
