//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{
    public partial class PlantBranch
    {
        [Key]
        public int PlantId { get; set; }

        [MaxLength(255)]
        [Column(TypeName = "varchar(255)")]
        [Required(ErrorMessage = "Plant Name is required")]
        public string PlantName { get; set; }

        [MaxLength(255)]
        [Column(TypeName = "varchar(1000)")]
        [Required(ErrorMessage = "Plant Address Line1 is required")]
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int CityId { get; set; }
        public string PinCode { get; set; }
        public string PANNo { get; set; }
        public string CSTNo { get; set; }
        public string GSTIN { get; set; }
        public string GSTType { get; set; }
        public string Remark { get; set; }
        public string Logo { get; set; }
        public bool IsActive { get; set; }
        public int CompanyId { get; set; }
        public string BranchType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
