//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PostingPeriod
    {
        [Key]
        public int PostingPeriodId { get; set; }
        public string PostingPeriodName { get; set; }
        public System.DateTime PostDateFrom { get; set; }
        public System.DateTime PostDateTo { get; set; }
        public System.DateTime DueDateFrom { get; set; }
        public System.DateTime DueDateTo { get; set; }
        public System.DateTime DocDateFrom { get; set; }
        public System.DateTime DocDateTo { get; set; }
        public System.DateTime StartFiscalDate { get; set; }
        public string FiscalYear { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int CompanyId { get; set; }
    }
}
