//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{  
    public partial class Warehouse
    {
        [Key]
        public int WarehouseId { get; set; }

        [MaxLength(255)]
        [Column(TypeName = "varchar(50)")]
        [Required(ErrorMessage = "Warehouse Code is required")]
        public string WarehouseCode { get; set; }

        [MaxLength(255)]
        [Column(TypeName = "varchar(255)")]
        [Required(ErrorMessage = "Warehouse Name is required")]
        public string WarehouseName { get; set; }
        public int PlantId { get; set; }

        [MaxLength(255)]
        [Column(TypeName = "varchar(500)")]
        [Required(ErrorMessage = "Warehouse Address Line1 is required")]
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int CityId { get; set; }
        public string PinCode { get; set; }
        public string PANNo { get; set; }
        public string Remark { get; set; }
        public bool IsDropShip { get; set; }
        public bool IsBinLoc { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
