//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{
    public partial class WithHoldingTax
    {
        [Key]
        public int WithHoldingTaxId { get; set; }
        public string WHTaxCode { get; set; }
        public string WHTaxName { get; set; }
        public string TDSType { get; set; }
        public string Section { get; set; }
        public decimal Threshold { get; set; }
        public decimal Surcharge { get; set; }
        public string Assessee { get; set; }
        public string Category { get; set; }
        public decimal BaseAmount { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public string BaseType { get; set; }
        public int PlantId { get; set; }
        public string ReturnType { get; set; }
        public string PurTDSAccount { get; set; }
        public string PurSurchargeAccount { get; set; }
        public string PurCessAccount { get; set; }
        public string PurHSCAccount { get; set; }
        public string SaleTDSAccount { get; set; }
        public string SaleSurchargeAccount { get; set; }
        public string SaleCessAccount { get; set; }
        public string SaleHSCAccount { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
