//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.Data
{
    public partial class ResponseGlobal
    {
        public int ResponseCode { get; set; }
        public string Message { get; set; }
        public dynamic Data { get; set; }
    }
   
}
