//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikasFashionsAPI.ViewModel
{
    public partial class UserRegister
    {
        [Required(ErrorMessage = "Name is required")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "User Code is required")]
        public string UserCode { get; set; }

        [Required(ErrorMessage = "Email is required")]
        public string Email { get; set; }
        public string Phone { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Role is required")]
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }

        //[Required(ErrorMessage = "Company is required")]
        //public int CompanyId { get; set; }

        //public string CompanyUserType { get; set; }
        public string BannerImage { get; set; }
        public string ProfileImage { get; set; }
    }
   
}
